# Autograd: Automatic Differentiation

In [16]:
import torch

In [17]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [18]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)

y was created as a result of a function, so it has a grad_fn

In [19]:
print(y.grad_fn)

Do more operations on y

In [20]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [21]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


backprop

In [22]:
out.backward(torch.tensor(3, dtype=torch.float))

In [23]:
print(x.grad)

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])


other example

In [24]:
x = torch.randn(3, requires_grad=True)
y=x*2
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([ 413.4076, -986.9014,  415.0273], grad_fn=<MulBackward>)


In [25]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


Stop autograd from tracking history on tensors that require gradient

In [26]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
