# Basic Syntax

In [1]:
import torch

create a matrix without initialization

In [2]:
x= torch.empty(5, 3)

In [3]:
print(x)

tensor([[-15231976.0000,         0.0000, -15231976.0000],
        [        0.0000,         0.0000,         0.0000],
        [        0.0000,         0.0000,         0.0000],
        [        0.0000,         0.0000,         0.0000],
        [        0.0000,         0.0000,         0.0000]])


create matrix with random initialization

In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4450, 0.1323, 0.0705],
        [0.6572, 0.7936, 0.7228],
        [0.7145, 0.9810, 0.0854],
        [0.5411, 0.7197, 0.3084],
        [0.0277, 0.1114, 0.4416]])


Construct a matrix filled with zeros and of dtype long

In [8]:
x=torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [11]:
x = torch.tensor([[5.5, 3], [3, 4]])
print(x)

tensor([[5.5000, 3.0000],
        [3.0000, 4.0000]])


In [12]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 0.3252,  0.9446,  0.0054],
        [-1.0654, -1.0976,  0.0498],
        [-0.6440, -0.0968, -0.0008],
        [-1.4751,  0.3657,  0.3640],
        [-0.5161,  1.6358,  0.1103]])


In [16]:
x.size()

torch.Size([5, 3])

## Operations

In [20]:
y = torch.rand(5, 3)
print(x+y)

tensor([[ 0.9679,  1.1497,  0.2693],
        [-0.6816, -0.2574,  0.1446],
        [-0.4738,  0.2837,  0.2542],
        [-0.7636,  0.4802,  0.7018],
        [-0.0737,  2.0843,  0.6190]])


In [21]:
print(torch.add(x,y))

tensor([[ 0.9679,  1.1497,  0.2693],
        [-0.6816, -0.2574,  0.1446],
        [-0.4738,  0.2837,  0.2542],
        [-0.7636,  0.4802,  0.7018],
        [-0.0737,  2.0843,  0.6190]])


In [23]:
result=torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 0.9679,  1.1497,  0.2693],
        [-0.6816, -0.2574,  0.1446],
        [-0.4738,  0.2837,  0.2542],
        [-0.7636,  0.4802,  0.7018],
        [-0.0737,  2.0843,  0.6190]])


In [24]:
y.add_(x)
print(y)

tensor([[ 0.9679,  1.1497,  0.2693],
        [-0.6816, -0.2574,  0.1446],
        [-0.4738,  0.2837,  0.2542],
        [-0.7636,  0.4802,  0.7018],
        [-0.0737,  2.0843,  0.6190]])


The underscores mark in-place operations

Slicing

In [25]:
y[:, 1]

tensor([ 1.1497, -0.2574,  0.2837,  0.4802,  2.0843])

Resizing

In [29]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
x = torch.randn(1)

In [31]:
print(x)

tensor([0.0003])


In [33]:
print(x.item())

0.00026096709189005196


Converting a Tensor to a NumPy Array

In [34]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [35]:
b= a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [36]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor

In [39]:
import numpy as np

In [40]:
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Cuda Tensors

In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z= x + y
    print(z)
    print(z.to("cpu", torch.double))
    